export const mainListItems = [
  {
    icon_title: "home-icon.svg",
    destination: "",
    name: "Dashboard",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "shopping-cart-icon.svg",
    destination: null,
    name: "Catalogue",
    notifications: 0,
    expandable: true,
    sub_list: [
      { name: "New Collection", destination: "new_collection" },
      { name: "Discounted", destination: "discounted" },
    ],
  },
  {
    icon_title: "list-icon.svg",
    destination: "orders",
    name: "Orders",
    notifications: 14,
    expandable: false,
  },
  {
    icon_title: "user-icon.svg",
    destination: "customers",
    name: "Customers",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "target-icon.svg",
    destination: null,
    name: "Marketing",
    notifications: 0,
    expandable: true,
    sub_list: [
      { name: "Discount codes", destination: "discount_codes" },
      { name: "Exit intent", destination: "exit_intent" },
      { name: "Checkout Features", destination: "checkout_features" },
      {
        name: "Post-purchase conversion",
        destination: "post_purchase_conversion",
      },
      { name: "Cart abandonment", destination: "cart_abandonment" },
      { name: "Timer checkout", destination: "timer_checkout" },
      { name: "Sell on Social", destination: "sell_on_social" },
      { name: "Special Offer", destination: "special_offer" },
      { name: "Seasonal Offer", destination: "seasonal_offer" },
    ],
  },
  {
    icon_title: "truck-icon.svg",
    destination: "delivery_options",
    name: "Delivery Options",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "dollar-sign-icon.svg",
    destination: "payment_options",
    name: "Payment Options",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "brush-icon.svg",
    destination: "store_design",
    name: "Store Design",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "credit-card-icon.svg",
    destination: "subscription",
    name: "Subscription",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "cog-planet-icon.svg",
    destination: "integrations",
    name: "Integrations",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "new-app-icon.svg",
    destination: "extensions",
    name: "Extensions",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "settings-icon.svg",
    destination: "settings",
    name: "Settings",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "log-out-icon.svg",
    destination: "log_out",
    name: "Log out",
    notifications: 0,
    expandable: false,
  },
];

export const extraListItems = [
  {
    icon_title: "help-circle-icon.svg",
    destination: "customer_support",
    name: "Customer Support",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "share-2-icon.svg",
    destination: "share_your_shop",
    name: "Share your shop",
    notifications: 0,
    expandable: false,
  },
  {
    icon_title: "eye-icon.svg",
    destination: "view_your_shop",
    name: "View your shop",
    notifications: 0,
    expandable: false,
  },
];

export const storeList = ["Fenoh Store", "Alibaba Store"];
